events{}

http{

    upstream face_counter_api_server {
        least_conn;
		server face_counter_service:8005;
    }
    
    # limit_req_zone $binary_remote_addr zone=face_count_rate:10m rate=300r/s;

    server {
        listen              443 ssl;
        server_name         127.0.0.1;

        ssl_certificate     /etc/nginx/ssl/fullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/privkey.pem;

        add_header Access-Control-Allow-Origin $http_origin always;
        add_header Access-Control-Allow-Methods 'GET, POST, PATCH, PUT, DELETE, OPTIONS' always;
        add_header Access-Control-Allow-Headers 'Content-Type, Accept, Authorization, X-Socket' always;

        # face-counter API

        location /face-counter/ {
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'DELETE, GET, OPTIONS, PATCH, POST, PUT';
                add_header 'Vary' 'Origin';
                add_header 'Access-Control-Allow-Headers' 'authorization, reqheader, accept, accept-encoding, authorization, content-type, dnt, origin, user-agent, x-csrftoken, x-requested-with, x-socket-id';
                add_header 'Access-Control-Max-Age' 86400;
                add_header 'Content-Type' 'text/html; charset=utf-8';
                return 200;
            }
            # limit_req zone=face_count_rate;
            # limit_req_status 429;
            proxy_pass http://face_counter_api_server;
        }

    }
}
