// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyZZeNHR8mfd6cE4EOmt1O7ila53eF-xI',
    appId: '1:86369065781:web:38b3890bcf29dc619d8a7c',
    messagingSenderId: '86369065781',
    projectId: 'cinteractionvc',
    authDomain: 'cinteractionvc.firebaseapp.com',
    storageBucket: 'cinteractionvc.appspot.com',
    measurementId: 'G-BSB43GRXB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH24lBXFPCfZclgbugmTmq43Zd5cTDfis',
    appId: '1:86369065781:android:a8fcc67f4fbfce4d9d8a7c',
    messagingSenderId: '86369065781',
    projectId: 'cinteractionvc',
    storageBucket: 'cinteractionvc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfNTE8QtidjY70YtuteJXABrstbyNUTmM',
    appId: '1:86369065781:ios:581b5ed1bf6038e49d8a7c',
    messagingSenderId: '86369065781',
    projectId: 'cinteractionvc',
    storageBucket: 'cinteractionvc.appspot.com',
    androidClientId: '86369065781-jjm8e0utp6jfl8p01ccdo73cqm2rfiuf.apps.googleusercontent.com',
    iosClientId: '86369065781-3ujc3l6agsn7ri36cc8faskj1vtj1de1.apps.googleusercontent.com',
    iosBundleId: 'com.cinteraction.vc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfNTE8QtidjY70YtuteJXABrstbyNUTmM',
    appId: '1:86369065781:ios:086f9e629586446e9d8a7c',
    messagingSenderId: '86369065781',
    projectId: 'cinteractionvc',
    storageBucket: 'cinteractionvc.appspot.com',
    androidClientId: '86369065781-jjm8e0utp6jfl8p01ccdo73cqm2rfiuf.apps.googleusercontent.com',
    iosClientId: '86369065781-vtaetkfvagqlfge8e5tislpeli1cs3pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinteractionVc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyZZeNHR8mfd6cE4EOmt1O7ila53eF-xI',
    appId: '1:86369065781:web:5b268592fd93ccb59d8a7c',
    messagingSenderId: '86369065781',
    projectId: 'cinteractionvc',
    authDomain: 'cinteractionvc.firebaseapp.com',
    storageBucket: 'cinteractionvc.appspot.com',
    measurementId: 'G-N0RCY6BV57',
  );
}
