# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    # Include the flutter action
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.16.6
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
      - name: Build Web Release   
        run: flutter build web --release
      - name: Flutter version
        run: flutter --version

    
      - name: Firebase Deployment
        # You may pin to the exact commit or the version.
        # uses: sws2apps/firebase-deployment@354a91d7bdc88e4dcb2c84774f7438c5a9276dce
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: cinteractionvc
      - name: Deploy to firebase  
        run: firebase deploy
                




    #   - name: FTP Deploy
    #     uses: SamKirkland/FTP-Deploy-Action@v4.3.5
    #     with:
    # # ftp server
    #       server: ${{ secrets.FTP_SERVER }}
    # # ftp username
    #       username:  ${{ secrets.FTP_USERNAME }}
    # # ftp password
    #       password: ${{ secrets.FTP_PASSWORD }}
    #       local-dir: build/web/
    #       exclude: |
    #         index.html
    #         .htaccess


    


