# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Include the flutter action
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.16.6
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      - name: Build Web Release
        run: flutter build web --release
      - name: Flutter version
        run: flutter --version

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: cinteractionvc
          channelId: live
